### ISSUE TITLE
咋修改自动打卡的时间

### ISSUE THREAD

**Issue by irimsky** [viewv/sduhealth#6]
改了main.yml里的cron之后到了那个时间好像并没有触发

**Comment by viewv** [comment]
确实很奇怪，今天我的也没有自动触发，按理说写法倒是对的，目前是在等明天看看会不会自动触发，非常奇怪的问题，也有可能是GitHub的时间不准或者故障，等明天看看。

**Comment by Singularity0909** [comment]
今天的自动执行也没有生效 Orz

**Comment by viewv** [comment]
已经有人反馈成功自动执行了，非常迷惑的问题，继续观察。

**Comment by nekomiao123** [comment]
我的自动执行成功了，但是比指定的时间晚了一个多小时，猜测应该不是不执行，就是时间不准，github action这个时间不准的问题我以前也遇到过

**Comment by Singularity0909** [comment]
同，比指定时间晚了一个小时

**Comment by viewv** [comment]
> 同，比指定时间晚了一个小时

难道我们其实住在 UTC +9 区？

**Comment by viewv** [comment]
我的也开始运行了，应该确认是 GitHub Action 运行问题，或者说我们真的在东九区，我将 Close issue
